name: Static Code Analysis

on:
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: 22

jobs:
  static_code_analysis:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: npm ci

      - name: Code Linting
        run: npm run lint
